### ISSUE TITLE
Is Kotlin 1.3 version without AndroidX available?

### ISSUE THREAD

**Issue by wellbranding** [RedApparat/Fotoapparat#340]
Hello, as far I see there is no version with Kotlin 1.3 but without AndroidX. The problem is that, we are using Fotoapparat in our SDK(android library), which can't be AndroidX, because many clients which use SDK **don't support AndroidX.** 

I wonder could were be additional build without AndroidX?  To be honest, it is important and greatly affects product. Can I contribute for such build? 

The app which uses AndroidX can easily integrate any support library by enabling **android.enableJetifier = true** ,which automatically converts all support libraries to androidX if possible. So version without Android X would be more practical for anyone to integrate.

 Thanks for your library, it is the most stable in comparison with other libraries and we will continue using it :)

**Comment by ZakTaccardi** [comment]
What's the significance of consuming this latest artifact of Fotoapparat in an app that still uses the support library without using `android.enableJetifier = true`?

**Comment by Diolor** [comment]
Hey. I know that it's annoying to go through the AndroidX migration pain but it's the only way forward... Sorry for the bad news. You may always make a custom FA build and replace android.x with android.support classes

**Comment by wellbranding** [comment]
Ok, I have done it. The problem is that I use Fotoapparat in our library, not application. How should I distribute our custom Fotoapparat with bintray plugin?   Should I build an aar file or something else?

**Comment by Diolor** [comment]
If you wish to distribute via jcenter, yes. You will need to register a new repo in jfrog bintray and upload it there (with a different group id, since io.fotoapparat is used by this project). From there people can download this custom version.

Take a look at our `deploy.gradle` file which we use. With this, correctly setup, you can run `./gradlew bintrayUpload`.

If you host this custom FA in github you might like to check `jitpack.io` (we used to use it in the past here)
